(function(){
 const sync=MuscleSync;let authKind='login',boardTimer=null,boardVersion='',accountId=null,boardFilter='all',boardMessages=[];
 const close=()=>button(icon('x'),'close','icon-button','aria-label="关闭"');
 const title=s=>`<div class="dialog-heading"><h2>${s}</h2>${close()}</div>`;
 const message=e=>{if(!dialog.open)showDialog(title('账号服务'));let box=dialog.querySelector('.account-error');if(!box){box=document.createElement('p');box.className='account-error';box.setAttribute('role','alert');dialog.querySelector('#dialog-content').append(box);}box.textContent=e.message;};
 function header(){let banner=document.querySelector('#debug-banner');if(sync.debug){if(!banner){banner=document.createElement('div');banner.id='debug-banner';document.querySelector('.topbar').after(banner);}const signature=sync.user?.id;if(banner.dataset.user!==signature){banner.dataset.user=signature;banner.innerHTML=`<div>${icon('flask-conical')}<span><strong>正在调试 ${esc(sync.user?.username||'连接中的模拟账号')}</strong><small>修改仅保存到此模拟账号 · 管理员身份保留</small></span></div>${button(icon('arrow-left')+'返回管理员','stop-debug','outline')}`;globalThis.lucide?.createIcons();}}else banner?.remove();document.querySelector('#account-name').textContent=sync.user?.username||'登录 / 注册';document.querySelector('#sync-label').textContent=sync.status;document.querySelector('.sidebar-foot')?.setAttribute('title',sync.user?'登录账号的档案会同步至服务器':'未登录档案仅保存在本机');}
 function account(kind){
  authKind=kind||(sync.setupRequired?'setup':'login');
  if(sync.user){const u=sync.user;showDialog(title('账号与同步')+`<h3>${esc(u.username)} <span class="tag">${u.role==='admin'?'管理员':'训练者'}</span></h3><div class="account-status">${esc(sync.status)}</div><p class="text-muted">档案、训练草稿和记录同步至本地服务器。管理员可查看这些记录；留言默认公开滚动展示，可由管理员隐藏。</p>${sync.conflict?`<div class="notice">其他设备已修改档案。两份数据不会自动合并；选择前会备份此设备版本。</div><div class="account-actions">${button('使用服务器版本','sync-remote','outline')}${button('用此设备版本覆盖','sync-local','outline')}</div>`:''}<div class="account-actions">${button(icon('refresh-cw')+'立即同步','sync-now','outline')}${button(icon('upload')+'导入此设备访客档案','import-guest','outline')}${u.role==='admin'||sync.debug?button(icon('users')+'用户管理','admin','outline')+button(icon('sliders-horizontal')+'回声设置','admin-echo','outline'):''}${sync.debug?button(icon('arrow-left')+'返回管理员','stop-debug','primary'):''}</div><label class="privacy-choice"><input id="model-consent" type="checkbox" ${sync.debug?'disabled':''} ${u.consent?'checked':''}><span>允许管理员将去标识的训练记录用于算法研究与校准。可随时关闭，已导出的副本需联系管理员删除；不会直接自动改变他人的计划。</span></label><p class="text-muted">退出后仍保留该账号的离线缓存。共享设备请使用浏览器访客模式。</p>${button(icon('log-out')+'退出账号','logout','outline')}`);return;}
  showDialog(title(authKind==='setup'?'初始化管理员':'账号登录')+(authKind!=='setup'?`<div class="auth-tabs">${button('登录','auth-login',authKind==='login'?'active':'outline')}${button('注册','auth-register',authKind==='register'?'active':'outline')}</div>`:'<p class="notice">首次启动：此账号将成为管理员。没有默认密码。</p>'+button('已有账号登录','auth-login','outline'))+`<form id="account-form"><label class="field"><span>独立用户名</span><input name="username" autocomplete="username" pattern="[A-Za-z0-9_]{3,24}" minlength="3" maxlength="24" required placeholder="字母、数字或下划线，3–24 位"></label><label class="field"><span>密码</span><input name="password" type="password" minlength="8" maxlength="128" required autocomplete="${authKind==='login'?'current-password':'new-password'}" placeholder="至少 8 位"></label>${authKind!=='login'?'<label class="privacy-choice"><input name="privacy" type="checkbox" required><span>我知道登录后档案与训练记录将保存到服务器。</span></label><details class="privacy-details"><summary>数据与留言说明</summary><p>管理员拥有档案与训练记录的管理权限。留言默认公开展示，可由管理员隐藏或恢复。访客档案仅在你主动导入后上传。</p></details><label class="privacy-choice"><input name="consent" type="checkbox"><span>自愿提供去标识训练记录用于算法研究（可选、可撤回）。</span></label>':''}<button type="submit" class="primary wide">${authKind==='setup'?'创建管理员':authKind==='register'?'创建账号':'登录'}</button></form>`);
 }
 async function board(){clearInterval(boardTimer);boardVersion='';boardFilter='all';showDialog(title('训练回声')+`<div class="echo-layout"><section class="echo-stream"><div class="echo-filters" role="group" aria-label="交流分类">${[['all','全部'],...Object.entries(echoTopics).map(([id,t])=>[id,t.name]),...(sync.user?.role==='admin'||sync.debug?[['hidden','已隐藏']]:[])].map(([id,name])=>button(name,'echo-filter',id==='all'?'selected':'',`data-filter="${id}" aria-pressed="${id==='all'}"`)).join('')}</div><div id="community-feed" class="community-feed" aria-live="polite"></div></section><aside class="echo-compose">${sync.user?`<form id="message-form" class="message-form"><h3>留下你的回声</h3><fieldset class="echo-compose-topics"><legend>话题</legend>${Object.entries(echoTopics).map(([id,t],i)=>`<label><input type="radio" name="topic" value="${id}" ${i===0?'checked':''}>${icon(t.icon)}${t.name}</label>`).join('')}</fieldset><label for="message-body">此刻想说</label><textarea id="message-body" name="body" maxlength="280" required placeholder="今天的小进步，或一个让训练更好的建议…"></textarea><div class="echo-compose-tools">${echoEmojiPicker()}<span id="echo-count">0 / 280</span></div><button type="submit" class="primary wide">${icon('send')}发布回声</button></form><p class="text-muted">默认公开显示。请勿发布密码、联系方式或他人的健康资料。</p>`:`<h3>你的想法，也在这里。</h3>${button('登录后参与','account','primary wide')}`}</aside></div>`);dialog.classList.add('echo-dialog');await refreshBoard(true);boardTimer=setInterval(()=>{if(dialog.open&&dialog.querySelector('#community-feed'))refreshBoard().catch(message);else clearInterval(boardTimer);},15000);}
 async function refreshBoard(force){const result=await sync.api(sync.user?'messages':'board');boardMessages=result.messages;renderBoard(force);}
 function renderBoard(force){const feed=dialog.querySelector('#community-feed');if(!feed)return;const version=JSON.stringify([boardFilter,boardMessages]);if(!force&&version===boardVersion)return;boardVersion=version;const scroll=feed.scrollTop,rows=boardMessages.filter(m=>boardFilter==='all'||boardFilter==='hidden'&&m.hidden||echoTopic(m)===boardFilter).slice().reverse();feed.innerHTML=rows.length?rows.map(m=>echoCard(m)).join(''):'<div class="echo-empty">这个话题还没有回声。</div>';feed.scrollTop=force?0:scroll;dialog.querySelectorAll('[data-action="echo-filter"]').forEach(el=>{el.classList.toggle('selected',el.dataset.filter===boardFilter);el.setAttribute('aria-pressed',String(el.dataset.filter===boardFilter));});globalThis.lucide?.createIcons();}
 async function admin(){const result=await sync.api('admin/users');showDialog(title('用户管理')+`<p class="notice">查看用户记录会写入管理员审计日志。训练资料仅用于管理；研究导出只包含自愿授权的用户。</p><div class="account-actions">${button(icon('sliders-horizontal')+'回声设置','admin-echo','outline')}${button(icon('download')+'下载每周档案备份','admin-backup','outline',sync.debug?'disabled title="请先返回管理员身份"':'')}${button(icon('download')+'导出授权研究数据','research-export','outline')}${button(icon('arrow-left')+'返回账号','account','outline')}</div><p class="backup-status" role="status">${!result.lastBackup||Date.now()-Date.parse(result.lastBackup)>=7*86400000?'本周待备份':'本周已生成备份'} · ${result.lastBackup?'上次生成 '+esc(new Date(result.lastBackup).toLocaleString('zh-CN')):'尚未生成'}。请确认文件已保存到本地。</p>`+result.users.map(u=>`<div class="admin-user"><div><strong>${esc(u.username)}</strong><small>${u.demo?'模拟账号':u.role==='admin'?'管理员':'训练者'} · ${u.sessions} 次记录 · ${u.consent?'研究已授权':'研究未授权'}</small></div><div class="admin-user-actions">${u.demo?button(icon('flask-conical')+'进入调试','start-debug','primary',`data-id="${u.id}" data-name="${esc(u.username)}"`):''}${button('查看记录','admin-user','outline',`data-id="${u.id}"`)}</div></div>`).join(''));}
 async function userRecords(id){const result=await sync.api('admin/users/'+id),d=result.data,p=d.profile;showDialog(title(esc(result.user.username)+' · 训练记录')+button(icon('arrow-left')+'返回用户列表','admin','outline')+`<div class="account-summary"><div><strong>${d.history.length}</strong><small>训练记录</small></div><div><strong>${d.session?'有':'无'}</strong><small>进行中训练</small></div></div><details><summary>档案与全部已存数据</summary><pre class="admin-json">${esc(JSON.stringify(d,null,2))}</pre></details>${p?`<p>${p.age} 岁 · ${p.weight} kg · ${p.experience==='trained'?'有经验':'新手'} · ${p.goal==='strength'?'力量':'增肌'}</p>`:'<p>尚未建立档案。</p>'}${d.history.slice(0,50).map(h=>`<article class="admin-record"><strong>${esc(h.date)} · ${esc(C.lifts.find(l=>l.id===h.lift)?.name||h.lift)} · ${esc(K.labels[h.mode]||h.mode)}</strong>${h.sets.filter(s=>s.done).map(s=>`<p>${esc(C.byId(s.exercise)?.name||s.exercise)}：${s.weight} ${esc(s.weightUnit||'kg')} × ${s.reps} ${esc(s.unit||'次')}</p>`).join('')}</article>`).join('')}`);}
 function download(value,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 document.addEventListener('click',async event=>{const t=event.target.closest('[data-action]');if(!t)return;const a=t.dataset.action;try{
  if(a==='account'){if(!sync.user){const result=await sync.api('auth/me');sync.setupRequired=result.setupRequired;}account();}if(a==='auth-login')account('login');if(a==='auth-register')account('register');
  if(a==='sync-now'){await sync.refresh();account();}
  if(a==='logout'){await sync.logout();dialog.close();toast('已退出，返回此设备访客档案');}
  if(a==='import-guest'&&confirm('用此设备的访客档案替换当前账号档案？当前账号会先备份在本机，其他设备将同步此结果。')){sync.importGuest();await sync.flush();account();}
  if(['sync-local','sync-remote'].includes(a)&&confirm(a==='sync-local'?'用此设备数据覆盖服务器版本？其他设备新增的记录可能丢失。':'使用服务器版本？此设备原数据将留在冲突备份中。')){await sync.resolve(a==='sync-local');account();}
  if(a==='start-debug'){t.disabled=true;try{await sync.startDebug(t.dataset.id);dialog.close();location.hash='overview';render();toast('已进入 '+sync.user.username+'，可以直接修改与记录训练');}finally{t.disabled=false;}}
  if(a==='stop-debug'){t.disabled=true;try{const result=await sync.stopDebug();dialog.close();location.hash='overview';render();toast(result.retainedLocally?'已返回管理员；过期调试的未同步数据仍保留在本机，重新进入该 demo 可继续同步':'已返回管理员，调试数据保存在对应 demo');}finally{t.disabled=false;}}
  if(a==='echo-filter'){boardFilter=t.dataset.filter;renderBoard(true);}
  if(a==='community')await board();if(a==='admin')await admin();if(a==='admin-user')await userRecords(t.dataset.id);
  if(a==='admin-backup'&&confirm('下载全部真实用户的档案和训练数据管理备份？文件未加密，请存放在私密位置，不要公开或上传到代码仓库。测试账号、密码和登录令牌不会导出；此操作不覆盖任何训练数据，也不授予算法研究权限。')){t.disabled=true;try{const archive=await sync.api('admin/backup','POST',{});download(archive,'jugetiezi-users-'+archive.createdAt.replace(/[:.]/g,'-')+'.json');await admin();toast('备份已生成，请确认浏览器下载完成');}finally{t.disabled=false;}}
  if(a==='research-export'&&confirm('导出当前授权用户的完整研究快照？模拟数据不包含在内。每周只使用最新快照重新生成样本；撤回授权后需停用相关旧样本和模型。文件未加密，仍可能关联到个人，不应公开传播。')){t.disabled=true;try{const snapshot=await sync.api('admin/research-export');download(snapshot,'big3-consented-research-'+snapshot.createdAt.replace(/[:.]/g,'-')+'.json');toast('已生成授权研究快照，不会自动训练或更改计划');}finally{t.disabled=false;}}
  if(a==='delete-message'&&confirm('删除这条留言？')){await sync.api('messages/'+t.dataset.id,'DELETE');await refreshBoard();await refreshRibbon();}
  if(a==='visibility-message'){await sync.api('messages/'+t.dataset.id,'PATCH',{hidden:t.dataset.hidden==='true'});await refreshBoard();await refreshRibbon();}
  if(a==='emoji'){const input=dialog.querySelector('#message-body');if(input.value.length+t.dataset.emoji.length<=280)input.setRangeText(t.dataset.emoji,input.selectionStart,input.selectionEnd,'end');input.dispatchEvent(new Event('input',{bubbles:true}));dialog.querySelector('.echo-emoji-more')?.removeAttribute('open');input.focus();}
 }catch(e){message(e);}});
 document.addEventListener('submit',async event=>{if(!['account-form','message-form'].includes(event.target.id))return;event.preventDefault();const form=event.target,b=form.querySelector('[type="submit"]');b.disabled=true;try{const f=new FormData(form);if(form.id==='account-form'){await sync.login(authKind,{username:f.get('username'),password:f.get('password'),privacyAccepted:f.has('privacy'),consent:f.has('consent')});form.reset();account();}else{await sync.api('messages','POST',{body:f.get('body'),topic:f.get('topic')||'training'});form.reset();const count=document.querySelector('#echo-count');if(count)count.textContent='0 / 280';boardFilter='all';await refreshBoard(true);await refreshRibbon();}}catch(e){message(e);}finally{b.disabled=false;}});
 document.addEventListener('change',async event=>{if(event.target.id!=='model-consent')return;try{await sync.consent(event.target.checked);}catch(e){event.target.checked=!!sync.user?.consent;message(e);}});
 window.addEventListener('sync-status',header);
 window.addEventListener('sync-data',()=>{try{const nextId=sync.user?.id||null;if(accountId!==nextId){viewingSession=true;viewFrozen=false;overrides={};planEdits={};addedExercises=[];accountId=nextId;resetRoutine();}data=store.load();loadError='';readiness=K.feedback(data,selectedDate)||{fatigue:2,pain:false};render();}catch(e){loadError=e.message;render();}});
 document.addEventListener('close',()=>clearInterval(boardTimer),true);
 sync.init();header();
})();
