/* Browser-only preview. Planning, catalog, geometry and persistence are shared with the mini program. */
const C=globalThis.MuscleCatalog,P=globalThis.MusclePlanner,A=globalThis.MuscleAnatomy,S=globalThis.MuscleScience,F=globalThis.MuscleFigures;
const qaName=new URLSearchParams(location.search).get('qa');
const storageSuffix=qaName!==null?'-qa-'+qaName:'';
const store=globalThis.MuscleStore.createStore({getStorageSync:key=>localStorage.getItem(key+storageSuffix),setStorageSync:(key,value)=>localStorage.setItem(key+storageSuffix,value)});
const app=document.querySelector('#app'),dialog=document.querySelector('#detail');
let data=globalThis.MuscleStore.empty(),loadError='',page='today',lift='squat',muscle='quads',side='front',equipment='全部器械',query='',filter='all',selectedDate=P.dateKey(),freeMode='',readiness={fatigue:2,pain:false},overrides={},planEdits={},viewingSession=true,currentPlan;
try{data=store.load();readiness=K.feedback(data,P.dateKey())||readiness;}catch(e){loadError=e.message;}
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<i data-lucide="${name}"></i>`;
const navs=[['overview','概览','layout-dashboard'],['today','今日训练','dumbbell'],['atlas','肌肉图谱','accessibility'],['history','训练记录','chart-no-axes-combined'],['profile','我的档案','user-round']];
const button=(label,action,cls='',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',3500);}
function error(message){let el=document.querySelector('#error');if(!el){el=document.createElement('div');el.id='error';el.className='error';app.prepend(el);}el.textContent=message;el.scrollIntoView({block:'nearest'});}
function commit(next){if(loadError)throw Error(loadError);const latest=store.load();if((latest.session?.id||null)!==(data.session?.id||null))throw Error('当前训练已在其他页面变化，请刷新后重试');store.save(next);data=next;render();}
function plan(){
 const p=K.prescription(data,lift,selectedDate,readiness,{mode:freeMode||undefined});
 const history=data.history.filter(r=>!P.validateRecord(r)&&r.date<=P.dateKey()).sort((a,b)=>b.date.localeCompare(a.date));
 p.exercises=p.exercises.map(e=>{
   const replacement=overrides[e.id];
   const selected=!e.main&&e.alternatives.includes(replacement)?P.prescribe(replacement,data.profile,history,p.mode,{sets:e.sets,reps:C.byId(replacement).unit==='秒'?25:10}):e;
   return planEdits[selected.id]||selected;
 });
 return p;
}
function heading(title,description,eyebrow,tag=''){const controls=page==='today'?`<div class="free-controls"><label>训练日期 <input id="today-date" type="date" value="${selectedDate}" max="2099-12-31"></label><button data-action="today-date" class="today-mark">今天</button><label>训练日类型 <select id="free-mode" ${data.session&&viewingSession?'disabled':''}><option value="" ${!freeMode?'selected':''}>按规划</option><option value="technique" ${freeMode==='technique'?'selected':''}>技术日</option><option value="volume" ${freeMode==='volume'?'selected':''}>容量日</option><option value="intensity" ${freeMode==='intensity'?'selected':''}>强度日</option><option value="recovery" ${freeMode==='recovery'?'selected':''}>恢复日</option><option value="test" ${freeMode==='test'?'selected':''}>冲刺日</option></select></label><p>${data.session&&viewingSession?'训练已开始，计划类型、重量和次数已冻结；结束或放弃后才能重新选择。':'可自由选择项目和训练日类型；系统仍会参考训练间隔、实际疲劳和已完成负荷。'}</p></div>`:'';return controls+`<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${page==='today'?selectedDate+'，练什么。':title}</h1><p>${description}</p></div>${tag?`<span class="tag">${icon('circle-dot')}${tag}</span>`:''}</div>`;}
function mapMarkup(){return `<div class="anatomy-pair"><canvas id="body-map" class="body-map" aria-label="${side==='front'?'正面':'背面'}肌肉图"></canvas><canvas id="body-map-other" class="body-map alternate" aria-label="另一侧肌肉图"></canvas></div>`;}
function sideButtons(){return `<div class="segmented">${button('正面','side',side==='front'?'selected':'','data-side="front"')}${button('背面','side',side==='back'?'selected':'','data-side="back"')}</div>`;}
function liftNavigation(){return `<div class="segments browse-lifts">${C.lifts.map(l=>button('查看'+l.name+'计划','lift','outline',`data-lift="${l.id}"`)).join('')}</div>`;}
function fatigueMarkup(){const f=S.fatigueInfo(readiness.fatigue);return `<div class="fatigue-summary"><strong>${f.value} · ${f.label}</strong><p>${f.description}</p><p>${f.action}</p></div><details class="fatigue-guide"><summary>1–5 档的判断依据</summary>${S.fatigueLevels.map(l=>`<p><b>${l.value} ${l.label}</b>：${l.description}</p>`).join('')}<p>主观准备度筛查，不是医学量表；5 档或疼痛优先休息。</p></details>`;}
function muscleButtons(ids){return `<div class="muscle-tags">${C.muscles.filter(m=>!ids||ids.includes(m.id)).map(m=>button(m.name,'muscle',muscle===m.id?'selected':'',`data-id="${m.id}"`)).join('')}</div>`;}
function scheduleMarkup(){const upcoming=K.rolling(data).filter(p=>p.exercises.length).slice(0,4);return `<div class="schedule-block"><h2>接下来</h2>${upcoming.map(d=>`<div class="log-row">${d.date} · ${C.lifts.find(l=>l.id===d.lift).name} · ${d.label}${button('查看','open-plan','link',`data-date="${d.date}"`)}</div>`).join('')}<p class="text-muted">保存实际训练后重新推演，不把建议计入训练量。</p></div>`;}
function exerciseRows(exercises){
 return exercises.map((e,i)=>`<div class="exercise-row"><span class="ex-number">${String(i+1).padStart(2,'0')}</span><div class="ex-copy">${button(esc(e.name),'detail','ex-name',`data-id="${e.id}"`)}<small>${e.sets?`休息 ${e.rest} 秒 · ${e.unit==='秒'?'保持姿势与呼吸':'保留 '+e.rir+' 次余力'}`:esc(e.en)}</small>
 ${e.sets?`<div class="plan-fields">${[['weight',e.weightUnit,'0.5'],['sets','组数','1'],['reps',e.unit,'1']].map(([key,label,step])=>`<label><span>${label}</span><input type="number" min="${key==='weight'?0:1}" max="${key==='sets'?8:key==='weight'?600:300}" step="${step}" value="${e[key]}" data-plan="${e.id}" data-field="${key}" aria-label="${e.name}计划${key==='weight'?'重量':key==='sets'?'组数':'次数'}"></label>`).join('')}</div><small class="load-source">${esc(e.source)}</small><small class="load-advice">${esc(e.advice||'')}</small>`:''}
 ${!e.main&&e.sets&&e.alternatives.length?button(`${icon('repeat-2')}替换动作`,'replace','link',`data-id="${e.id}"`):''}</div>${!e.sets?`<span class="tag">${e.equipment}</span>`:''}${button(icon('accessibility'),'detail','icon-button',`data-id="${e.id}" title="查看${e.name}示意" aria-label="查看${e.name}示意"`)}</div>`).join('');
}
function today(){
 if(data.session&&viewingSession)return liftNavigation()+sessionPage();
 currentPlan=plan();const l=C.lifts.find(l=>l.id===lift),p=currentPlan;const controls=`<div class="free-controls"><label>训练日期 <input id="today-date" type="date" value="${selectedDate}" max="2099-12-31"></label><label>训练日类型 <select id="free-mode"><option value="">按规划</option><option value="technique">技术日</option><option value="volume">容量日</option><option value="intensity">强度日</option><option value="recovery">恢复日</option><option value="test">冲刺日</option></select></label><p>可自由选择项目和训练日类型；系统仍会参考训练间隔、实际疲劳和已完成负荷。</p></div>`;
 return heading('今天，练什么。','专注每一组，让进步有据可循。','YOUR DAILY PRACTICE','今日计划')+`${data.session?`<div class="notice row"><span>当前有 ${C.lifts.find(l=>l.id===data.session.lift).name} 训练未结束，查看计划不会丢失记录。</span>${button('继续当前训练','resume','outline')}</div>`:''}<div class="dashboard"><section><div class="lifts">${C.lifts.map(l=>`<button class="lift-tile ${lift===l.id?'active':''}" data-action="lift" data-lift="${l.id}" aria-pressed="${lift===l.id}"><div class="equipment-photo" role="img" aria-label="${l.name}器械"></div><div class="lift-info"><div><strong>${l.name}</strong><small>${l.en}</small></div>${icon(lift===l.id?'circle-check':'arrow-up-right')}</div></button>`).join('')}</div>
 <div class="plan-band"><div class="row"><span class="tag ${p.mode==='intensity'?'red':''}">${icon('layers-2')}${p.label}</span><span class="eyebrow">${l.en} / DAY</span></div>${p.mode==='setup'?`<div class="empty"><h2>你的第一组，<br>从这里开始。</h2><p>填写年龄、体重和训练经验。<br>有 PB 就填，没有也能开始训练。</p>${button(`建立训练档案 ${icon('arrow-right')}`,'profile','primary wide')}</div>`:`<h2>${l.subtitle}训练</h2>${p.exercises.length?`<div class="metrics"><div><div class="metric-value">${p.estimatedMinutes}<small>分钟</small></div><div class="metric-label">预计用时</div></div><div><div class="metric-value">${p.exercises.length}<small>个</small></div><div class="metric-label">训练动作</div></div><div><div class="metric-value">${p.rpe}</div><div class="metric-label">目标 RPE</div></div></div>`:''}${p.blockedReason?`<div class="notice">${esc(p.blockedReason)}</div>`:''}<p class="text-muted">${esc(p.reason)}</p>`}</div>
 <div class="section-head"><h2>${p.previewOnly?'后续参考计划':p.exercises.length?'今日动作':'主项与辅助动作'}</h2><span class="text-muted">${p.exercises.length?p.exercises.length+' 个动作':'先了解，再开始'}</span></div>${p.exercises.length?`<div class="warmup">${icon('flame')}<span>热身 5–8 分钟，主项逐组接近工作重量。<br>热身组不计入工作组；辅助动作保留 2–4 次余力。</span></div>${exerciseRows(p.exercises)}<details class="set-rationale"><summary>为什么工作组重量和次数相同？</summary><p>${S.straightSets}</p></details>${button(p.previewOnly?'仅预览 · 当天重新评估':data.session?'请先结束当前训练':`开始本次训练 ${icon('arrow-right')}`,'start','primary wide',!p.canStart||data.session?'disabled':'')}`:p.mode==='rest'?`<div class="notice">${esc(p.reason)}</div>`:exerciseRows([C.byId(lift),...{squat:['goblet','split'],bench:['dbbench','pushup'],deadlift:['rdl','row']}[lift].map(C.byId)])}</section>
 <section class="map-panel"><div class="section-head"><h2>目标肌群</h2>${sideButtons()}</div>${mapMarkup()}<div class="muscle-legend"><span class="swatch"></span> 本次训练涉及肌群</div>${muscleButtons(l.muscles)}${button(`探索完整肌肉图谱 ${icon('arrow-up-right')}`,'atlas','link wide')}${data.profile?`<div class="readiness"><div class="row"><label for="fatigue">训练前疲劳程度</label><span class="tag">${readiness.fatigue} / 5</span></div><input id="fatigue" type="range" min="1" max="5" value="${readiness.fatigue}" aria-label="疲劳程度">${fatigueMarkup()}<label class="switch-label">今天有疼痛或明显不适<input id="pain" type="checkbox" ${readiness.pain?'checked':''}></label></div>`:''}${scheduleMarkup()}</section></div>`;
}
function atlas(){const m=C.muscles.find(m=>m.id===muscle);const items=C.exercises.filter(e=>e.muscles.includes(muscle)&&(equipment==='全部器械'||e.equipment===equipment)&&(!query||(e.name+' '+e.en).toLowerCase().includes(query.toLowerCase())));return heading('从肌肉，找到动作。','选择一个部位，找到适合你的训练动作。','EXPLORE YOUR MOVEMENT',C.exercises.length+' 个动作')+`<div class="atlas-layout"><section class="atlas-left">${sideButtons()}${mapMarkup()}<div class="muscle-legend"><span class="swatch"></span>${m.name}</div>${muscleButtons()}</section><section class="atlas-right"><div class="section-head"><h2>${m.name}</h2><select id="equipment" aria-label="器械筛选">${C.equipment.map(e=>`<option ${equipment===e?'selected':''}>${e}</option>`).join('')}</select></div><input id="search" placeholder="搜索当前肌群动作" value="${esc(query)}" aria-label="搜索动作">${items.length?exerciseRows(items):'<div class="empty text-muted">没有匹配动作，请调整筛选条件。</div>'}${button(`进入${C.lifts.find(l=>l.id===m.lift).name}训练 ${icon('arrow-right')}`,'related','dark wide')}<div class="notice">动作图谱为简化示意。先选择可控负荷，在动作稳定的范围内训练。</div></section></div>`;}
function field(name,label,value,attributes=''){return `<label class="field"><span>${label}</span><input name="${name}" value="${esc(value)}" ${attributes}></label>`;}
function profile(){const p=data.profile||{age:'',weight:'',experience:'beginner',goal:'strength',days:[1,3,5],increment:2.5,pb:{}};return heading('你的起点。','不与别人比较，把每一次进步留给自己。','ATHLETE PROFILE','仅本机保存')+`<form id="profile-form"><div class="form-layout"><section><h2>基础资料</h2><div class="grid2">${field('age','年龄 / 岁',p.age,'type="number" min="18" max="100" step="1" required placeholder="18–100"')}${field('weight','体重 / kg',p.weight,'type="number" min="30" max="350" step="0.1" required placeholder="例如 75"')}</div><label class="field"><span>训练经验</span><select name="experience"><option value="beginner" ${p.experience==='beginner'?'selected':''}>新手 / 重新开始</option><option value="trained" ${p.experience==='trained'?'selected':''}>有规律训练经验</option></select></label><label class="field"><span>主要目标</span><select name="goal"><option value="strength" ${p.goal==='strength'?'selected':''}>力量提升</option><option value="muscle" ${p.goal==='muscle'?'selected':''}>肌肉增长</option></select></label><div class="field"><span>每周可训练日</span><div class="days">${['一','二','三','四','五','六','日'].map((label,i)=>`<label class="day"><input type="checkbox" name="days" value="${(i+1)%7}" ${p.days.includes((i+1)%7)?'checked':''} aria-label="周${label}">${label}</label>`).join('')}</div></div><label class="field"><span>最小总重量增量 / kg（两侧合计）</span><select name="increment">${[0.5,1,1.25,2.5,5].map(n=>`<option value="${n}" ${Number(p.increment)===n?'selected':''}>${n} kg</option>`).join('')}</select></label><div class="notice">年龄、体重不直接换算安全重量。65 岁及以上默认技术适应模板；有伤病或健康限制时请先接受专业评估。</div></section><section><div class="section-head"><h2>三大项 PB</h2><span class="text-muted">可全部留空</span></div><p class="text-muted" style="margin-bottom:20px">1 次为实测单次 PB；2–10 次用于估算。<br>不必为填写资料而测试极限。</p>${C.lifts.map(l=>{const pb=p.pb[l.id]||{weight:'',reps:1,date:P.dateKey()};return `<div class="pb"><div class="pb-heading"><h3>${l.name}</h3><span>${l.en}</span></div><div class="grid2">${field(l.id+'Weight','总重量 / kg',pb.weight,'type="number" min="1" max="600" step="0.5" placeholder="暂不填写"')}${field(l.id+'Reps','完成次数',pb.reps,'type="number" min="1" max="10" step="1"')}</div>${field(l.id+'Date','记录日期',pb.date,`type="date" max="${P.dateKey()}"`)}</div>`;}).join('')}</section></div><div class="form-actions"><button type="submit" class="primary">${icon('check')}保存训练档案</button><span class="text-muted">保存后重新评估下一次计划，历史记录保持不变。</span></div></form><section class="section"><div class="section-head"><h2>数据与隐私</h2><span class="tag">${icon('shield-check')}不上传个人数据</span></div><p class="text-muted">不采集姓名、手机号或位置。清理存储或换机会丢失本地记录，请定期导出。浏览器预览和微信小程序存储相互独立。</p><div class="form-actions">${button(icon('download')+'导出 JSON 备份','export','outline')}${button(icon('upload')+'恢复备份','import-panel','outline')}</div><div id="backup-area" class="backup-area" hidden><label class="field"><span>JSON 备份内容（恢复会替换当前资料和历史）</span><textarea id="backup" placeholder="粘贴备份内容"></textarea></label>${button('验证并恢复','import','dark')}</div></section>`;}
function history(){const records=data.history.filter(r=>filter==='all'||r.lift===filter);const total=records.reduce((sum,r)=>sum+r.sets.filter(s=>s.done&&C.byId(s.exercise).unit!=='秒').reduce((sum,s)=>sum+Number(s.weight)*Number(s.reps),0),0);return heading('力量，有迹可循。','每一组真实的记录，都是下一次训练的参考。','TRAINING HISTORY')+`<div class="history-stats"><div><div class="metric-value">${data.history.length}<small>次</small></div><div class="metric-label">累计训练</div></div><div><div class="metric-value">${Math.round(total).toLocaleString()}<small>kg·次</small></div><div class="metric-label">当前筛选记录负荷</div></div></div><p class="text-muted">按录入重量 × 次数统计；不含计时动作、自身体重及双侧换算。</p><div class="muscle-tags divider">${[{id:'all',name:'全部'},...C.lifts].map(l=>button(l.name,'filter',filter===l.id?'selected':'',`data-id="${l.id}"`)).join('')}</div>${records.length?records.map(r=>`<div class="log-row"><div>${button(C.lifts.find(l=>l.id===r.lift).name+' · '+P.modes[r.mode],'record','',`data-id="${esc(r.id)}"`)}<p>${r.date} · ${r.sets.length} 组 · ${r.completed?'主项目标已完成':'部分完成，周期未推进'}</p></div><div class="row"><span class="tag">RPE ${esc(r.rpe)}</span>${button(icon('arrow-up-right'),'record','icon-button',`data-id="${esc(r.id)}" aria-label="查看训练记录" title="查看记录"`)}</div></div>`).join(''):`<div class="empty"><h2>还没有训练记录。</h2><p>不需要完美的开始，先完成你的第一组。</p>${button(`开始一次训练 ${icon('arrow-right')}`,'today','primary divider')}</div>`}`;}
function sessionPage(){const s=data.session;return heading('专注这一组。','填写实际重量和次数，再勾选完成。自重动作填 0 kg。','SESSION IN PROGRESS',P.modes[s.mode])+`<section class="session-layout"><p class="text-muted">杠铃填总重，哑铃填单只重量，单侧动作每侧计次。未保存的输入需勾选完成后才写入本地。</p><div class="timer" id="timer"><div><small>组间休息</small><strong id="timer-value">0:00</strong></div>${button('跳过休息','skip','outline')}</div><div class="set-head"><span>动作 / 组</span><span>重量 kg</span><span>次 / 秒</span><span>完成</span></div>${s.sets.map((r,i)=>`<div class="set-row ${r.done?'done':''}"><div>${button(esc(r.name),'detail','ex-name',`data-id="${r.exercise}"`)}<small>第 ${r.index} 组 · ${r.unit}</small></div><input type="number" min="0" max="600" step="0.5" value="${esc(r.weight)}" placeholder="实际" data-set="${i}" data-field="weight" aria-label="${esc(r.name)}第${r.index}组重量"><input type="number" min="1" max="300" step="1" value="${esc(r.reps)}" data-set="${i}" data-field="reps" aria-label="${esc(r.name)}第${r.index}组次数">${button(icon(r.done?'circle-check':'circle'),'toggle-set','check',`data-index="${i}" aria-label="${esc(r.name)}第${r.index}组${r.done?'取消完成':'完成'}" aria-pressed="${r.done}"`)}</div>`).join('')}<div class="readiness"><div class="row"><label for="rpe">主项用力程度 RPE</label><span class="tag">${s.rpe} / 10</span></div><input id="rpe" type="range" min="1" max="10" step="1" value="${s.rpe}"><p class="text-muted">7 ≈ 还能做 3 次；8 ≈ 还能做 2 次；10 ≈ 无法再完成。</p></div><div class="form-actions">${button(icon('check')+'结束并保存','finish','primary')}${button('放弃本次','discard','outline')}</div></section>`;}
function render(){page=location.hash.slice(1)||'overview';if(!navs.some(n=>n[0]===page))page='overview';document.querySelector('#nav').innerHTML=navs.map(([id,name,i])=>`<a href="#${id}" class="nav-item ${page===id?'active':''}" ${page===id?'aria-current="page"':''}>${icon(i)}<span>${name}</span></a>`).join('');document.querySelector('#page-label').textContent=navs.find(n=>n[0]===page)[1];const dateInput=document.querySelector('#date');dateInput.value=selectedDate;dateInput.max='2099-12-31';app.innerHTML=(loadError?`<div id="error" class="error">${esc(loadError)}</div>`:'')+({overview,today,atlas,profile,history}[page])();globalThis.lucide?.createIcons();drawMap();renderExtras();coachExtras();globalThis.lucide?.createIcons();tick();}
function drawMap(){document.querySelectorAll('.body-map').forEach((canvas,i)=>{const rect=canvas.getBoundingClientRect();if(!rect.width)return;const view=i?(side==='front'?'back':'front'):side;const ratio=devicePixelRatio||1;canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const selected=page==='today'?C.lifts.find(l=>l.id===lift).muscles:[muscle];A.draw(ctx,rect.width,rect.height,view,selected);canvas.onclick=e=>{ctx.save();ctx.setTransform(1,0,0,1,0,0);const id=A.hit(ctx,e.offsetX,e.offsetY,rect.width,rect.height,view);ctx.restore();if(id){muscle=id;side=view;if(page==='today')location.hash='atlas';render();}};});}
function tick(){const timer=document.querySelector('#timer');if(!timer)return;const n=Math.max(0,Math.ceil(((data.session?.deadline||0)-Date.now())/1000));timer.hidden=n===0;timer.style.display=n?'flex':'none';document.querySelector('#timer-value').textContent=Math.floor(n/60)+':'+String(n%60).padStart(2,'0');}
function showDialog(content){document.querySelector('#dialog-content').innerHTML=content;globalThis.lucide?.createIcons();dialog.showModal();}
function showExercise(id){const ex=C.byId(id);if(!ex)return;figurePhase=0;showDialog(`<div class="row" data-exercise="${id}"><div><h2>${ex.name}</h2><p class="text-muted">${ex.en} · ${F.figures[id].view}</p></div>${button(icon('x'),'close','icon-button','aria-label="关闭" title="关闭"')}</div><canvas id="exercise-canvas" class="exercise-canvas" aria-label="${ex.name}动作阶段示意"></canvas><div class="figure-stage-nav">${button(icon('chevron-left'),'figure-prev','icon-button','aria-label="上一阶段"')}<span id="phase-label">起始姿势</span>${button(icon('chevron-right'),'figure-next','icon-button','aria-label="下一阶段"')}</div><p class="text-muted">${F.figures[ex.id].cue}</p><ol>${ex.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="notice">${ex.caution}</div>`);drawFigure(ex.id);}
document.addEventListener('click',event=>{
 const target=event.target.closest('[data-action]');if(!target)return;const a=target.dataset.action,id=target.dataset.id;
 try{
  if(navs.some(n=>n[0]===a)){location.hash=a;return;}
  if(a==='close'){dialog.close();return;}
  if(a==='today-date'){selectedDate=P.dateKey();freeMode='';planEdits={};render();return;}
  if(a==='lift'){viewingSession=false;lift=target.dataset.lift;side=lift==='deadlift'?'back':'front';muscle=C.lifts.find(l=>l.id===lift).muscle;overrides={};planEdits={};render();}
  if(a==='side'){side=target.dataset.side;if(page==='atlas'&&C.muscles.find(m=>m.id===muscle).side!==side)muscle=side==='back'?'upperback':'chest';render();}
  if(a==='muscle'){muscle=id;side=C.muscles.find(m=>m.id===id).side;if(page==='today')location.hash='atlas';render();}
  if(a==='detail')showExercise(id);
  if(a==='science')showScience();
  if(a==='related'){viewingSession=false;lift=C.muscles.find(m=>m.id===muscle).lift;side=lift==='deadlift'?'back':'front';location.hash='today';}
  if(a==='replace'){const ex=C.byId(id);showDialog(`<div class="row"><h2>替换 ${ex.name}</h2>${button(icon('x'),'close','icon-button','aria-label="关闭"')}</div><p class="text-muted divider">替换后重量需重新选择，不沿用原动作负荷。</p>${ex.alternatives.map(alt=>button(C.byId(alt).name,'choose-replacement','outline wide',`data-id="${id}" data-replacement="${alt}"`)).join('')}`);}
  if(a==='choose-replacement'){const original=Object.keys(overrides).find(k=>overrides[k]===id)||id;overrides[original]=target.dataset.replacement;planEdits={};dialog.close();render();}
  if(a==='resume'){viewingSession=true;render();}
  if(a==='start'){if(data.session)throw Error('已有进行中的训练');const p=plan();if(!p.canStart)throw Error(p.reason);const s=K.session(p);if(p.mode==='test'){if(!confirm('已安排保护者或安全杆、无疼痛，且热身动作稳定？不满足请取消测试。'))return;s.protectionConfirmed=true;}viewingSession=true;commit({...data,session:s});}
  if(a==='toggle-set'){const s=structuredClone(data.session),r=s.sets[Number(target.dataset.index)];if(s.date!==P.dateKey())throw Error('这份训练草稿已跨日，请先保存已完成组或放弃，再重新评估今天的计划。');if(!r.done&&P.validateRecord({...s,completed:false,sets:[{...r,done:true}]}))throw Error('请填写本组实际重量与次数。自重动作填 0 kg。');r.done=!r.done;s.deadline=r.done?Date.now()+r.rest*1000:0;commit({...data,session:s});}
  if(a==='skip')commit({...data,session:{...data.session,deadline:0}});
  if(a==='finish'){if(!confirm('只保存已勾选的实际完成组。实际日期：'+(data.session.actualDate||P.dateKey())+'。现在结束训练？'))return;store.finish(data.session,data.session.actualDate||P.dateKey());data=store.load();planEdits={};location.hash='overview';render();toast('训练已保存，两周建议已重新计算');}
  if(a==='discard'){if(confirm('放弃本次尚未保存的训练？历史记录不受影响。'))commit({...data,session:null});}
  if(a==='filter'){filter=id;render();}
  if(a==='record'){const r=data.history.find(r=>r.id===id);showDialog(`<div class="row"><h2>${r.date} · ${C.lifts.find(l=>l.id===r.lift).name}</h2>${button(icon('x'),'close','icon-button','aria-label="关闭"')}</div><p class="text-muted divider">${r.completed?'主项目标已完成':'部分完成，周期未推进'} · RPE ${esc(r.rpe)}</p>${r.sets.map(s=>`<div class="log-row"><span>${esc(C.byId(s.exercise).name)}</span><span>${esc(s.weight)} kg × ${esc(s.reps)} ${C.byId(s.exercise).unit}</span></div>`).join('')}${button(icon('trash-2')+'删除这次记录','remove','link wide',`data-id="${esc(r.id)}"`)}`);}
  if(a==='remove'&&confirm('删除这次训练记录？这会影响后续周期判断。')){commit({...data,history:data.history.filter(r=>r.id!==id)});dialog.close();}
  if(a==='export'){const blob=new Blob([store.exportRaw()],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='three-lift-'+P.dateKey()+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('备份已导出');}
  if(a==='import-panel')document.querySelector('#backup-area').hidden=false;
  if(a==='import'){const raw=document.querySelector('#backup').value;if(!confirm('将替换本机资料与历史，并清除进行中的训练。已保留当前备份？'))return;store.importRaw(raw);loadError='';data=store.load();render();toast('备份已恢复');}
 }catch(e){error(e.message);}
});
document.addEventListener('change',event=>{const t=event.target;try{
 if(t.id==='date'&&t.value){selectedDate=t.value;freeMode='';planEdits={};render();}
 if(t.id==='today-date'&&t.value){selectedDate=t.value;planEdits={};render();}
 if(t.id==='free-mode'){freeMode=t.value;planEdits={};render();}
 if(t.id==='fatigue'||t.id==='pain'){if(t.id==='fatigue')readiness.fatigue=Number(t.value);else readiness.pain=t.checked;store.feedback({...readiness,date:P.dateKey(),soreness:readiness.soreness||{}});data=store.load();planEdits={};render();}
 if(t.id==='equipment'){equipment=t.value;render();}
 updateTrainingInput(t);
 if(t.dataset.rir!==undefined){const session=structuredClone(data.session);session.sets[Number(t.dataset.rir)].rir=t.value===''?null:Number(t.value);commit({...data,session});}
 if(page==='profile')refreshEstimates();
 if(t.id==='rpe')commit({...data,session:{...data.session,rpe:Number(t.value)}});
 }catch(e){error(e.message);}
});
function updateTrainingInput(t){ if(t.dataset.set!==undefined){const index=Number(t.dataset.set);data.session.sets[index]=S.reviseSet(data.session.sets[index],t.dataset.field,t.value);const row=t.closest('.set-row');row.querySelector('[data-field="reps"]').value=data.session.sets[index].reps;row.classList.remove('done');row.querySelector('.check').setAttribute('aria-pressed','false');row.querySelector('.check').innerHTML=icon('circle');renderExtras();globalThis.lucide?.createIcons();}
 if(t.dataset.plan){const id=t.dataset.plan;const ex=currentPlan.exercises.find(e=>e.id===id);const updated=S.reviseSet({...ex,targetRir:ex.rir},t.dataset.field,t.value);planEdits[id]=updated;currentPlan.exercises=currentPlan.exercises.map(e=>e.id===id?updated:e);const row=t.closest('.exercise-row');row.querySelector('[data-field="reps"]').value=updated.reps;row.querySelector('.load-advice').textContent=updated.advice||'';}
}
document.addEventListener('input',event=>{const t=event.target;try{updateTrainingInput(t);}catch(e){error(e.message);}if(page==='profile')refreshEstimates();if(t.id==='search'){query=t.value;render();const next=document.querySelector('#search');next.focus();next.setSelectionRange(query.length,query.length);}});
document.addEventListener('submit',event=>{if(event.target.id!=='profile-form')return;event.preventDefault();try{const form=new FormData(event.target),pb={};C.lifts.forEach(l=>{if(form.get(l.id+'Weight')!=='')pb[l.id]={weight:Number(form.get(l.id+'Weight')),reps:Number(form.get(l.id+'Reps')),date:form.get(l.id+'Date')};});const profile={age:Number(form.get('age')),weight:Number(form.get('weight')),experience:form.get('experience'),goal:form.get('goal'),days:form.getAll('days').map(Number),increment:Number(form.get('increment')),pb};const message=P.validateProfile(profile);if(message)throw Error(message);planEdits={};commit({...data,profile});toast('训练档案已保存');}catch(e){error(e.message);}});
function estimateMarkup(estimate,profile){if(!estimate)return '<p class="text-muted">填写 1–10 次的有效记录后显示估算。</p>';return `<div class="text-muted">${estimate.measured?'实测单次 PB':'估算单次 PB / e1RM'}</div><strong>${estimate.range} <small>kg</small></strong><p>Epley ${estimate.epley} · Brzycki ${estimate.brzycki}</p><p>保守训练基准 ${S.trainingMax(profile,estimate)} kg${estimate.relative?' · '+estimate.relative+' 倍体重':''}</p><p class="text-muted">接近极限、动作合格的记录才适用；范围为公式差异，不是置信区间。</p>`;}
function refreshEstimates(){const form=document.querySelector('#profile-form');if(!form)return;const p={age:form.elements.age.value,weight:form.elements.weight.value,experience:form.elements.experience.value};C.lifts.forEach(l=>{const el=document.querySelector('[data-estimate="'+l.id+'"]');if(el)el.innerHTML=estimateMarkup(S.estimatePB(form.elements[l.id+'Weight'].value,form.elements[l.id+'Reps'].value,p.weight),p);});}
function renderExtras(){
 if(page==='today'&&data.session&&viewingSession){const header=document.querySelector('.set-head span:nth-child(2)');const repsHeader=document.querySelector('.set-head span:nth-child(3)');if(header)header.textContent='重量 / 单位';if(repsHeader)repsHeader.textContent='次数';document.querySelectorAll('.set-row').forEach((row,i)=>{const input=row.querySelector('input[data-field="weight"]');const unit=data.session.sets[i]?.weightUnit||'kg';if(input)input.setAttribute('aria-label',`${data.session.sets[i]?.name||''}实际重量（${unit}）`);});}
 if(page==='today'&&data.session&&viewingSession&&data.session.requestedMode){const box=document.createElement('div');box.className='notice mode-adjustments';box.textContent=`用户选择：${K.labels[data.session.requestedMode]||data.session.requestedMode} · 系统实际：${K.labels[data.session.effectiveMode]||data.session.effectiveMode}${data.session.adjustments?.length?'；'+data.session.adjustments.join('；'):''}`;document.querySelector('.session-layout')?.prepend(box);}
 if(page==='profile'){
   document.querySelectorAll('.pb').forEach((el,i)=>{if(!el.querySelector('.pb-summary')){const box=document.createElement('div');box.className='pb-summary';box.dataset.estimate=C.lifts[i].id;el.append(box);}});refreshEstimates();
   if(!app.querySelector('[data-action="science"]'))app.querySelector('.form-actions').insertAdjacentHTML('beforeend',button(icon('book-open')+'计算依据','science','outline'));
 }
 if(page==='today'&&!(data.session&&viewingSession)&&currentPlan?.estimate){const box=document.createElement('div');box.className='pb-summary';box.innerHTML=estimateMarkup(currentPlan.estimate,data.profile)+button('训练计算依据','science','link');app.querySelector('.plan-band').append(box);}
 if(page==='today'&&currentPlan?.requestedMode){const box=document.createElement('div');box.className='notice mode-adjustments';box.innerHTML=`用户选择：${esc(K.labels[currentPlan.requestedMode]||currentPlan.requestedMode)} · 系统实际：${esc(currentPlan.label)}${currentPlan.adjustments?.length?'<br>'+currentPlan.adjustments.map(esc).join('<br>'):''}`;app.querySelector('.plan-band')?.append(box);}
 if(page==='atlas'){const selected=C.muscles.find(m=>m.id===muscle);if(selected.note){let p=app.querySelector('.anatomy-note');if(!p){p=document.createElement('p');p.className='notice anatomy-note';app.querySelector('.atlas-left').append(p);}p.textContent=selected.note;}}
 if(data.session&&viewingSession&&page==='today')document.querySelectorAll('.set-row').forEach((el,i)=>{const row=data.session.sets[i];let extra=el.querySelector('.set-extra');if(!extra){extra=document.createElement('div');extra.className='set-extra';el.append(extra);}extra.innerHTML=`<span>${esc(row.weightUnit||C.byId(row.exercise).weightUnit)} · ${esc(row.source||'既有训练记录')}</span><label ${row.unit==='秒'?'hidden':''}>实际剩余次数 <select data-rir="${i}" aria-label="${esc(row.name)}第${row.index}组剩余次数"><option value="">未记录</option>${[0,1,2,3,4,5].map(n=>`<option value="${n}" ${row.rir!==null&&row.rir!==undefined&&Number(row.rir)===n?'selected':''}>${n===5?'5+':n} 次</option>`).join('')}</select></label><span>${esc(row.advice||'')}</span>`;});
 globalThis.lucide?.createIcons();
}
function showScience(){showDialog(`<div class="row"><h2>训练计算依据</h2>${button(icon('x'),'close','icon-button','aria-label="关闭"')}</div><div class="notice">当前是有文献依据的可校准起点，不保证个人最优效果。年龄、体重不对已完成的 PB 加成；首次辅助动作试重没有经过验证的跨动作换算公式。</div><p class="text-muted divider">Epley = 重量 × (1 + 次数 / 30)；Brzycki = 重量 × 36 / (37 − 次数)。单次记录直接视为实测值。保守基准取两者低值的 90%，新手或 65 岁以上取 85%，属于产品安全余量。</p><p class="text-muted divider">工作重量从目标次数和余力反算，并按器械增量向下取整；修改重量后次数随之调整。技术与恢复日另行降重。辅助动作按实际记录递增，未记录余力时不自动加重。</p>${S.sources.map(s=>`<div class="section"><a target="_blank" rel="noopener noreferrer" href="${s.url}">${s.title} ↗</a><p class="text-muted">${s.note}</p></div>`).join('')}`);}
function drawFigure(id){const canvas=document.querySelector('#exercise-canvas');if(!canvas||!id)return;const rect=canvas.getBoundingClientRect();canvas.width=rect.width*devicePixelRatio;canvas.height=rect.height*devicePixelRatio;const ctx=canvas.getContext('2d');ctx.scale(devicePixelRatio,devicePixelRatio);F.draw(ctx,rect.width,rect.height,id,figurePhase);document.querySelector('#phase-label').textContent=figurePhase?(id==='plank'?'保持姿势':'关键终点'):'起始姿势';}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});window.addEventListener('resize',()=>{drawMap();if(dialog.open){const title=dialog.querySelector('h2')?.textContent;const ex=C.exercises.find(e=>e.name===title);if(ex)drawFigure(ex.id);}});setInterval(tick,1000);render();
