const K=globalThis.MuscleCoach;
let selectedPlan=null,figurePhase=0;
function overview(){
 const o=K.overview(data,selectedDate);
 const metrics=o.achievements.map(a=>`<article class="lift-summary"><h2>${a.name}</h2><div class="metric-value">${a.measured?a.measured.weight:'—'}<small>kg 实测单次最佳</small></div><p class="text-muted">${a.measured?esc(a.measured.date+' · '+a.measured.source):'尚无单次 PB 记录'}</p><div class="estimated">e1RM ${a.latest?a.latest.range+' kg':'—'}</div><p class="text-muted">${a.latest?esc(a.latest.date+' · '+a.latest.weight+' kg × '+a.latest.reps+' · '+a.latest.confidence):'完成多次组后显示估算'}</p>${a.points.length?`<div class="mini-trend">${a.points.slice(-8).map(p=>`<div><span style="height:${Math.max(8,p.low/Math.max(...a.points.map(x=>x.high))*60)}px"></span><small>${p.low}</small><small>${p.date.slice(5)}</small></div>`).join('')}</div>`:''}</article>`).join('');
 return heading('训练概览','实际记录驱动 · 两周滚动安排','TRAINING OVERVIEW')+(!data.profile?`<div class="notice">建立基础档案后开始规划。${button('建立档案','profile','primary')}</div>`:'')+`<div class="summary-grid">${metrics}</div><section class="section"><div class="section-head"><h2>下一次建议</h2>${button('自由选择训练','today','outline')}</div>${o.next?`<h2>${o.next.date} · ${C.byId(o.next.lift).name} · ${o.next.label}</h2><p class="text-muted">${esc(o.next.reason)}</p>${button('查看逐组计划','open-plan','primary',`data-date="${o.next.date}"`)}`:'<p class="text-muted">当前没有可执行建议，请检查档案与恢复状态。</p>'}</section><section class="section"><div class="section-head"><h2>未来两周</h2><span class="text-muted">建议，不是已完成记录</span></div><div class="calendar">${o.schedule.map(p=>`<button class="calendar-day ${p.mode} ${p.date===P.dateKey()?'today':''} ${p.date===selectedDate?'selected-date':''}" data-action="open-plan" data-date="${p.date}"><small>${p.date.slice(5)}</small><strong>${p.lift?C.lifts.find(l=>l.id===p.lift).name:p.label}</strong><span>${p.lift?p.label:''}</span></button>`).join('')}</div></section><section class="section"><h2>恢复与反馈</h2><p class="text-muted">基于已记录负荷、时间与主观反馈的分档估计，不是生理恢复率。</p>${button('记录今天状态','feedback','outline')}<div class="recovery-list">${o.recovery.map(m=>`<div><strong>${m.name}</strong><span class="tag ${m.level==='rest'?'red':''}">${m.label}</span><p class="text-muted">${esc(m.reason)}</p></div>`).join('')}</div></section><section class="section"><h2>近八周训练量</h2><p class="text-muted">仅主项实际成功工作组；热身不计。三项分别统计，不混合器械标重。</p><div class="summary-grid">${o.trends.map(t=>`<article class="lift-summary"><h3>${t.name} · 近 28 天 ${t.count} 次</h3><div class="mini-trend">${t.weeks.map(w=>`<div title="${w.start} 至 ${w.end}：${w.sets} 组，${w.volume} kg·次"><span style="height:${w.volume?Math.max(3,w.volume/Math.max(...t.weeks.map(x=>x.volume),1)*80):0}px"></span><small>${w.sets} 组</small><small>${w.volume}</small><small>${w.end.slice(5)}</small></div>`).join('')}</div><p class="text-muted">每列为一周：工作组 / kg·次</p></article>`).join('')}</div></section><section class="section"><h2>最近训练</h2>${o.recent.length?o.recent.map(r=>`<div class="log-row"><span>${r.date} · ${C.lifts.find(l=>l.id===r.lift).name}</span><span>${r.sets.filter(s=>s.done).length} 组 · ${r.completed?'完成目标':'部分完成'}</span></div>`).join(''):'<p class="text-muted">尚无训练记录。</p>'}</section>`;
}
function openPlan(date){
 const p=K.rolling(data,selectedDate).find(p=>p.date===date);if(!p)return;selectedPlan=p;
 showDialog(`<div class="row"><h2>${date} · ${p.label}</h2>${button(icon('x'),'close','icon-button','aria-label="关闭"')}</div><p class="notice">${esc(p.reason)}</p>${p.exercises.map(e=>`<div class="section"><h3>${e.name}</h3>${e.prescribedSets.map(s=>`<p>第 ${s.index} 组 · ${s.weight===null?'待试重':s.weight+' '+e.weightUnit} × ${s.reps} ${e.unit} · ${e.rir==null?'静态保持':'预计还能做 '+s.rir+' 次'} · 休息 ${s.rest} 秒</p>`).join('')}${button('查看动作','detail','link',`data-id="${e.id}"`)}</div>`).join('')}${p.lift?`<div class="form-actions">${button('查看此日训练','view-selected','outline')}${button('今天练此项目','train-selected','primary')}${button('延期','defer','outline')}${button('跳过这一天','skip-plan','outline')}</div>`:''}`);
}
function feedbackDialog(){sorenessDialog();}
function manualDialog(){retroDialog();}
document.addEventListener('click',event=>{const t=event.target.closest('[data-action]');if(!t)return;try{
 const a=t.dataset.action;
 if(a==='open-plan')openPlan(t.dataset.date);
 if(a==='feedback')feedbackDialog();
 if(a==='manual')manualDialog();
 if(a==='view-selected'){selectedDate=selectedPlan.date;readiness=K.feedback(data,selectedDate)||{fatigue:2,pain:false};freeMode='';lift=selectedPlan.lift;viewingSession=false;overrides={};planEdits={};dialog.close();location.hash='today';render();}
 if(a==='train-selected'){selectedDate=P.dateKey();readiness=K.feedback(data,selectedDate)||{fatigue:2,pain:false};freeMode='';lift=selectedPlan.lift;viewingSession=false;overrides={};planEdits={};dialog.close();location.hash='today';render();}
 if(a==='skip-plan'){store.event({id:selectedPlan.planId||selectedPlan.date+':'+selectedPlan.lift,kind:'skip',date:selectedPlan.date,lift:selectedPlan.lift});data=store.load();dialog.close();render();}
 if(a==='skip-today'){const p=plan();if(!p.skipAllowed)throw Error('该计划不可直接跳过');store.event({id:p.planId||p.date+':'+p.lift,kind:'skip',date:p.date,lift:p.lift});data=store.load();render();toast('已跳过，不计实际负荷；两周建议已更新');}
 if(a==='defer')showDialog(`<h2>延期训练</h2><form id="defer-form">${field('date','期望训练日',K.add(selectedPlan.date,1),`type="date" min="${K.add(selectedPlan.date,1)}" required`)}<p class="text-muted">届时按实际负荷重新评估，不保证沿用原处方。</p><button class="primary">保存延期</button></form>`);
 if(a==='request-test'){const st=K.testStatus(data,lift);if(!st.eligible)throw Error(st.reason);store.event({id:'test:'+Date.now(),kind:'test',date:P.dateKey(),lift});data=store.load();render();toast('已进入准备阶段；完成减量后再评估');}
 if(a==='next-attempt'){store.updateSession(K.nextAttempt(data.session,data.profile));data=store.load();render();}
 if(a==='stop-test'){store.updateSession({...data.session,stopTest:true});data=store.load();render();}
 if(a==='figure-prev'||a==='figure-next'){const ex=C.byId(dialog.querySelector('[data-exercise]')?.dataset.exercise);if(!ex)return;figurePhase=(figurePhase+(a==='figure-next'?1:-1)+ex.media.phases.length)%ex.media.phases.length;drawFigure(dialog.querySelector('[data-exercise]')?.dataset.exercise);}
 }catch(e){error(e.message);}});
document.addEventListener('submit',event=>{const id=event.target.id;if(!['feedback-form','defer-form','manual-form'].includes(id))return;event.preventDefault();try{const form=new FormData(event.target);
 if(id==='feedback-form'){readiness={fatigue:Number(form.get('fatigue')),pain:form.has('pain'),soreness:Object.fromEntries(C.muscles.map(m=>[m.id,Number(form.get(m.id))]))};store.feedback({...readiness,date:event.target.dataset.date});}
 if(id==='defer-form')store.event({id:selectedPlan.planId||selectedPlan.date+':'+selectedPlan.lift,kind:'defer',date:selectedPlan.date,lift:selectedPlan.lift,to:form.get('date')});
 if(id==='manual-form'){const d=store.load();const exercise=form.get('exercise');d.history.unshift({id:'manual:'+Date.now(),date:form.get('date'),lift:form.get('lift'),mode:'manual',completed:false,rpe:7,sets:[{exercise,loadConvention:C.byId(exercise).loadConvention,unit:C.byId(exercise).unit,weightUnit:C.byId(exercise).weightUnit,weight:Number(form.get('weight')),reps:Number(form.get('reps')),done:true,rir:null}]});store.save(d);}
 data=store.load();planEdits={};dialog.close();render();}catch(e){error(e.message);}});
function coachExtras(){
 if(data.session&&viewingSession&&page==='today')document.querySelectorAll('.set-row').forEach((el,i)=>{const row=data.session.sets[i];const flags=document.createElement('div');flags.className='set-extra';flags.innerHTML=`<label><input type="checkbox" data-row-flag="${i}" data-flag="quality" ${row.quality!==false?'checked':''}>动作合格</label><label><input type="checkbox" data-row-flag="${i}" data-flag="success" ${row.success!==false?'checked':''}>成功完成（失败时取消）</label>`;el.append(flags);});
 if(page==='today'){
  const section=document.createElement('div');section.className='section';section.innerHTML=button('补记实际训练','manual','outline')+button('记录肌群酸痛','feedback','outline');
  if(!(data.session&&viewingSession)&&plan().skipAllowed)section.innerHTML+=button('跳过恢复 / 减量日','skip-today','outline');
  if(data.profile&&!data.session){const st=K.testStatus(data,lift);section.innerHTML+=`<h3>测试准备</h3><p class="text-muted">${st.reason}</p>${button(data.settings.maxTesting?'申请单次测试准备':'申请次极限评估准备','request-test','outline',st.eligible?'':'disabled')}`;}
  app.append(section);
  if(data.session&&viewingSession){const box=document.createElement('div');box.className='section';box.innerHTML=`<label class="field">实际训练日期<input id="actual-date" type="date" max="${P.dateKey()}" value="${data.session.actualDate||P.dateKey()}"></label>`+(data.session.mode==='test'?`<p class="notice">最多三次。失败、疼痛或动作失控立即停止加重。成功但仍轻松的单次是实际成绩，不证明已到极限。</p>${button('下一次尝试','next-attempt','outline')}${button('停止测试','stop-test','outline')}`:'');app.append(box);}
 }
 if(page==='profile'){const box=document.createElement('label');box.className='switch-label section';box.innerHTML=`主动开启单次 PB 测试（有经验者）<input type="checkbox" id="max-testing" ${data.settings.maxTesting?'checked':''}>`;app.append(box);}
}
document.addEventListener('change',event=>{try{
 if(event.target.dataset.rowFlag!==undefined){const s=structuredClone(data.session);const row=s.sets[Number(event.target.dataset.rowFlag)];row[event.target.dataset.flag]=event.target.checked;if(s.mode==='test'&&!event.target.checked)s.stopTest=true;store.updateSession(s);data=store.load();}
 if(event.target.id==='max-testing'){const d=store.load();d.settings.maxTesting=event.target.checked;store.save(d);data=store.load();}
 if(event.target.id==='actual-date'){store.updateSession({...data.session,actualDate:event.target.value});data=store.load();}
}catch(e){error(e.message);}});
